set( GLEW_ROOT_DIR ${OGLW_ROOT}/deps/glew-2.1.0 )
set( GLEW_INCLUDE_DIR ${GLEW_ROOT_DIR}/include )
set( ENV{GLEW_INCLUDE_DIR} ${GLEW_INCLUDE_DIR} )

set( GLEW_INCLUDE_DIRS ${GLEW_ROOT_DIR}/include )
